"""
2026/01/14 huggingface.co/SakanaAI/TinySwallow-1.5B-Instruct-GGUF:latestをダウンロードします。


"""

import subprocess
import sys

def setup_model():
    # 1. 規約の表示
    terms_text = """
======================================================================
[TERMS AND CONDITIONS / 利用規約]

日本語:
1. 本ソフトウェアは、SakanaAI が公開している
   「TinySwallow-1.5B」モデルを Ollama を通じて利用します。
   本ソフトウェアには AI モデル本体は含まれておらず、
   モデルのダウンロードおよび利用は利用者自身の責任で行われます。
2. 本ソフトウェアが利用する AI によって生成された回答の
   正確性、完全性、安全性については一切保証されません。
3. 利用者は、SakanaAI が定める TinySwallow-1.5B のライセンス条件、
   ならびに Ollama の利用規約および関連するオープンソースライセンス
   （Apache License 2.0 を含む）を遵守する必要があります。
4. 本ソフトウェアの使用または使用不能により生じたいかなる損害についても、
   開発者は一切の責任を負いません。
5. 利用者は、本ソフトウェアを犯罪行為、差別的表現の生成、または公序良俗に反する目的で使用してはなりません。

English:
1. This software uses the "TinySwallow-1.5B" model published by SakanaAI through Ollama.
   This software does not include the AI ​​model itself, and downloading and using the model is at the user's own risk.
2. No guarantee is made regarding the accuracy, completeness, or safety of answers generated by the AI ​​used by this software.
3. Users must comply with the TinySwallow-1.5B license terms set forth by SakanaAI, 
   as well as Ollama's terms of use and related open source licenses (including the Apache License 2.0).
4. The developer assumes no responsibility for any damages arising from the use of or inability to use this software.
5. Usage for illegal activities, generating harmful content, or infringing upon the rights of third parties is strictly prohibited.

======================================================================
    """
    print(terms_text)

    # 2. 同意の確認
    user_input = input("To agree and start download, type 'ok': \n規約に同意してダウンロードを開始するには 'ok' と入力してください:--> ")

    if user_input.lower() != 'ok':
        print("\nInstallation cancelled. / インストールを中止しました。")
        sys.exit()

    # 3. モデルのダウンロード開始
    model_full_name = "huggingface.co/SakanaAI/TinySwallow-1.5B-Instruct-GGUF:latest"
    print(f"\nStarting download: {model_full_name}")
    print("This may take a few minutes depending on your connection...")

    try:
        # subprocessを使ってOllamaのコマンドを直接実行
        # progressを表示するためにそのまま標準出力に流す
        subprocess.run(["ollama", "pull", model_full_name], check=True)
        
        print("\n[Success] Download complete! / ダウンロードが完了しました！")
        
        # オプション: 使いやすいように短い名前でコピーを作成
        print("Configuring local alias 'tinyswallow'...")
        subprocess.run(["ollama", "cp", model_full_name, "tinyswallow"], check=True)
        print("Ready to use! / 準備が整いました。")

    except FileNotFoundError:
        print("\n[Error] Ollama is not installed. Please install Ollama first.")
        print("Ollamaが見つかりません。先にOllamaのインストールを完了させてください。")
    except subprocess.CalledProcessError as e:
        print(f"\n[Error] Download failed. / ダウンロードに失敗しました: {e}")

if __name__ == "__main__":
    setup_model()